### ISSUE TITLE
docker - improve image generation

### ISSUE THREAD

**Issue by pmauduit** [georchestra/georchestra#2171] opened 2018-09-20 08:21 UTC
To help customizing the official docker images, it would be interesting to provide the webapps in the docker container already unzipped in the `webapp/` directory. Looking at the current build process:

* https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/src/docker/Dockerfile#L7
* https://github.com/georchestra/georchestra/blob/18.06/mapfishapp/pom.xml#L606-L617

I don't know if maven allows us to do this easily, but a directory in `target/` should contain the actual unzipped webapp. We could try to use it instead of using the war artifact.

**Comment by fvanderbiest** [comment] 2019-09-27 14:12
Duplicate of #2577

**Closed by fvanderbiest** 2019-09-27 14:12 UTC
Labels: enhancement, priority-top
