### ISSUE TITLE
console - passwordRecovery fails when db was shut down then restarted

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2195] opened 2018-10-05 13:40 UTC
/console/account/passwordRecovery?email=me%40provider.com then reports:

![screenshot from 2018-10-05 15-38-06](https://user-images.githubusercontent.com/265319/46538610-bb7d0000-c8b4-11e8-86e8-1e513580901b.png)
![screenshot from 2018-10-05 15-38-33](https://user-images.githubusercontent.com/265319/46538615-bfa91d80-c8b4-11e8-9099-4078530f808a.png)

**Comment by fvanderbiest** [comment] 2018-10-05 13:41
Restarting the console fixes the issue, but the expected behavior would be that the db connection pool is smart enough to recreate failing connections (use c3p0 ?)

**Comment by fvanderbiest** [comment] 2018-10-05 13:55
To be fixed on 16.12

**Comment by cmangeat** [comment] 2018-10-09 13:49
atlas, console-tpl and extractor app also use com.mchange.v2.c3p0.ComboPooledDataSource.

**Comment by fvanderbiest** [comment] 2018-10-09 13:54
...which should do the job IIUC ?

**Comment by groldan** [comment] 2019-01-28 14:53
So I couldn't reproduce this as-is, but this is what I found:
- it looks like the issue is reported against 16.12 but I couldn't run 16.12 (the docker build fails on that branch and there seems not to be published docker tags other than latest)
- On master, it's unlikely that a `GET` call to `/console/account/passwordRecovery?` (`PasswordRecoveryFormController.setupForm()`) would throw any JDBC related exception as it doesn't hit it. `POST` (`PasswordRecoveryFormController.generateToken()`) does a couple of db interactions (by means of `UserTokenDao.exists()/delete()/insertToken()`).
- More importantly, that stacktrace, unless there's a repeatable way to reproduce, is most likely unrelated to the request in question as it's *just a warning* issues by c3p0, most times asynchronously, indicating that the client code is still using a connection that the pool already discarded because it's thrown an exception before. In this case, at some point in a transactional JPA method, the operation failed becuase it was forcedly closed.
- Since there are commands (e.g. `AdvancedDelegationDao.findByRole()`) that don't close the connections, statements, and resultsets it uses, most probably the above stack trace happens when the c3p0 connection gets automatically closed.

That said, the only way I could reproduce something similar, which can very well happen on a live instance, was with some hacking to match the timing between a DAO command was assigned a connection and the time is gets executed, closing the connections in-between.
This is a risk given the way these DAO commands are implemented, using a Connection as argument instead of a DataSource, it could happen that the connection was deemed valid when the client code got it from the pool but becomes invalid while the command is running. A safer approach would be for the commands to get a DataSource and the execute() method to grab, use, and close the connection atomically.

**Comment by groldan** [comment] 2019-01-31 12:40
Closing, fixed by #2436

**Closed by groldan** 2019-01-31 12:40 UTC
Labels: 16.12, bug, priority-top
