### ISSUE TITLE
Docker -  GN admin console not available

### ISSUE THREAD

**Issue by davinciagf** [georchestra/georchestra#1787] opened 2017-10-04 08:43 UTC
With the docker installation (latest docker image) and the use of default login/password ("testadmin"), the admin console of GN isn't completely available. Only the metadata tab of this admin is shown:
![capture1](https://user-images.githubusercontent.com/576292/31165892-072990a6-a8ed-11e7-93ab-945773c9636c.JPG)
No specific error in the console or in the docker log.
The ldapadmin interface is availble and references the "testadmin" profile
![capture2](https://user-images.githubusercontent.com/576292/31166716-eccf0eea-a8ef-11e7-9af7-79aecd452df8.JPG)

Thanks

**Comment by pmauduit** [comment] 2017-10-04 08:48
What is the XML output of the following webservice ?

http://yourgeorchestra/geonetwork/srv/eng/xml.info?type=me

**Comment by davinciagf** [comment] 2017-10-04 08:57
The profile is RegisteredUser, this explains the issue!
How to modify this profile ?

`<info><me authenticated="true"><profile>RegisteredUser</profile><username>testadmin</username><id>219</id><name>Test</name><surname>ADMIN</surname><email>psc+testadmin@georchestra.org</email><organisation>geOrchestra</organisation><hash>0b0ef2aa164421a74e49856a93268a4c</hash></me><env><baseURL>/geonetwork</baseURL><node>srv</node></env></info>`

**Comment by pmauduit** [comment] 2017-10-04 09:07
It seems that something is wrong either ldap side or GN side. When a user connects onto the CAS server, GN will check the user profile by itself onto the LDAP server, given the username:

https://github.com/georchestra/datadir/blob/16.12/geonetwork/geonetwork.properties#L47-L54

There has been some changes with groups in the new versions of geOrchestra, but IIRC if testadmin is member of the `GN_ADMIN` group, then it should be administrator on GN (which seems to be the case in regards of your screenshots). Could you check in your georchestra datadir, the content of the file `geonetwork/geonetwork.properties` ?

**Comment by davinciagf** [comment] 2017-10-04 09:18
```
# geonetwork datadir subdirs
geonetwork.dir=/mnt/geonetwork_datadir
geonetwork.config.dir=${geonetwork.dir}/config/
geonetwork.schema.dir=${geonetwork.config.dir}/schema_plugins/
geonetwork.lucene.dir=${geonetwork.dir}/index/
geonetwork.spatial.dir=${geonetwork.lucene.dir}
geonetwork.thesauri.dir=${geonetwork.config.dir}/codelist/
geonetwork.data.dir=${geonetwork.dir}/data/metadata_data/
geonetwork.svn.dir=${geonetwork.dir}/data/metadata_subversion/
geonetwork.resources.dir=${geonetwork.dir}/data/resources/
geonetwork.upload.dir=${geonetwork.dir}/data/upload/
geonetwork.formatter.dir=${geonetwork.dir}/data/formatter/
geonetwork.htmlcache.dir=${geonetwork.resources.dir}/htmlcache/

# database configuration
jdbc.host=database
jdbc.port=5432
jdbc.database=georchestra
jdbc.schema=geonetwork
jdbc.username=geonetwork
jdbc.password=georchestra

jdbc.basic.maxActive=33
jdbc.basic.maxWait=200
jdbc.basic.maxOpenPreparedStatements=1200

# ldap configuration (config-security/config-security-ldap.xml)
ldap.base.provider.url=ldap://ldap:389
ldap.base.dn=dc=georchestra,dc=org
ldap.security.principal=cn=admin,dc=georchestra,dc=org
ldap.security.credentials=secret
ldap.base.dn.pattern=uid={0}

ldap.sync.user.search.base=ou=users
ldap.sync.user.search.filter=(&(objectClass=*)(mail=*@*)(givenName=*))
ldap.sync.user.search.attribute=uid
ldap.privilege.create.nonexisting.groups=true
ldap.privilege.create.nonexisting.users=true
ldap.sync.group.search.base=ou=roles
ldap.sync.group.search.filter=(&(objectClass=groupOfMembers)(cn=EL_*))
ldap.sync.group.search.attribute=cn
ldap.sync.group.search.pattern=EL_(.*)

ldap.sync.cron=0 * * * * ?
ldap.sync.startDelay=60000

ldap.privilege.import=true
ldap.privilege.search.group.queryprop=member
ldap.privilege.search.group.query=(&(objectClass=groupOfMembers)(member=uid={0},${ldap.base.search.base},${ldap.base.dn})(cn=EL_*))
ldap.privilege.search.group.object=ou=roles
ldap.base.search.base=ou=users
ldap.privilege.search.privilege.pattern=GN_(.*)
ldap.privilege.search.privilege.query=(&(objectClass=groupOfMembers)(member=uid={0},${ldap.base.search.base},${ldap.base.dn})(cn=GN_*))
ldap.privilege.search.privilege.object=ou=roles``
```

**Comment by pmauduit** [comment] 2017-10-23 09:50
Reproduced in several environments (also reported by Rennes-Metropole here [private]: https://github.com/camptocamp/georchestra-rennes-configuration/issues/628).

The issue seems to be caused by the memberOf overlay which kindof breaks the wildcard search on attributes when they are composing the Distinguished Name (which is the case for groups / privileges). 

A workaround to fix only the privilege lookup is to remove the `(cn=GN_*)` condition in the `ldap.privilege.search.privilege.query` variable definition. But this won't solve the group import (`cn=EL_*`).

**Comment by fvanderbiest** [comment] 2017-12-22 09:42
@pmauduit status of this issue for 17.12 ?

**Comment by pmauduit** [comment] 2017-12-22 13:44
Seems working now on sandbox (based on master) testadmin has access to the GN admin interface.

**Comment by fvanderbiest** [comment] 2017-12-22 13:50
okay, closing then.

**Comment by fvanderbiest** [comment] 2017-12-29 08:45
Reopening, since I could reproduce on a local docker setup, compiling the `georchestra-gn3-master` branch.

**Comment by fvanderbiest** [comment] 2018-02-07 12:03
Fixed with https://github.com/georchestra/datadir/commit/742528b775aff9814ad151697a065c18f42d2cca

**Closed by fvanderbiest** 2018-02-07 12:03 UTC
Labels: bug, priority-top
