### ISSUE TITLE
console - org and role pages should display user list & enable membership management

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2080] opened 2018-06-14 09:52 UTC
On pages `/console/manager/#!/org/XXX/infos` and `/console/manager/#!/role/XXX/infos` (or maybe in another tab) an administrator should be able to see & manage member users.

**Comment by fvanderbiest** [comment] 2018-06-14 09:53
GeoBretagne and CRAIG have a strong interest for this feature.

**Comment by landryb** [comment] 2018-06-28 15:02
Now that i started playing with the console in master, this is definitely a feature we need. And since the members of an org/role are already stored in the ldap, i guess we just need the UI glue ?

**Comment by fvanderbiest** [comment] 2018-06-28 15:39
> i guess we just need the UI glue ?

That's it. Maybe custom services will be required to handle membership in batch, I don't know ATM.

**Comment by fvanderbiest** [comment] 2018-06-28 15:42
Could you specify here the complete requirements for this UI ? That would help a lot :-)

**Comment by landryb** [comment] 2018-06-28 15:59
Well i guess on an org/role page, being able to see the current member list, with a red tick box next to each of them to remove a member from the org/role, and an autocomplete field to add members not yet in the current org/role ? I'll discuss it tmrw with my colleagues to draft something.

Dunno if there are some integrity checks to do (ie not being able to remove a delegated admin from the group he admins ? the manager thing ?)

**Comment by landryb** [comment] 2018-06-29 12:09
from an org/role page, we need to:
* see the member list (enventually with pagination for roles with hundreds of users, ie USER ?)
* the member name is a link to the user page
* as it's done for org membership on the user page
  * a cross allows to remove a member
  * an autocomplete field/dropdown allows to add a member

while here, would there be a way for a user to *see* the details of his org (ie coverage, member list, etc...) ? right now he only sees the org name.

**Comment by landryb** [comment] 2018-07-04 09:38
Dupe of #1590 but with a broader scope, also applying to roles ?

**Comment by fvanderbiest** [comment] 2018-07-04 09:40
right

**Comment by fvanderbiest** [comment] 2018-07-12 12:06
> while here, would there be a way for a user to see the details of his org (ie coverage, member list, etc...) ? right now he only sees the org name.
> 
> Sure, but this would qualify for a separate issue (so we have room to discuss it in details). Thanks :-)

To be discussed on #2125

**Closed** 2018-09-07 08:16 UTC
Labels: 2018
