### ISSUE TITLE
No annotation layer when map context is load

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/georchestra#1548] opened 2016-11-15 08:45 UTC
Hello,
Annotation layer is removed when you draw something and you load new context before close annotation window. 

Step : 
- Load annotation addon
- Open annotation menu
- Draw point or line or what you need
- Click on "Workspace" / Click on "Load a map context" / select and load default context (do not close menu of annotation addon)
- Click on "Load"
BUG ==> The last draw is not visible and when you draw again, no items appears because annotation layer has been removed when i load new map context but addon was not reload.

It's possible to fix it by add "removed" event on annotation layer. So, when layer is removed, if annotation addon is already open we can add to map the layer again ?

I have tried this solution and, thing the problem was resolved.

**Comment by fvanderbiest** [comment] 2016-11-15 08:48
which branch / release ?

**Comment by Gaetanbru** [comment] 2016-11-15 09:13
Bug exist in : https://sdi-stable.georchestra.org/mapfishapp/
And in my local geOrchestra v 15.12.

**Comment by Gaetanbru** [comment] 2017-03-11 01:14
Not a bug.
Layer is just send to the back when user load wmc. 
Is it not better to close annotation addon when wms is load to entirely respecte wmc ?

**Comment by fvanderbiest** [comment] 2017-03-13 13:27
> Is it not better to close annotation addon when wms is load to entirely respecte wmc ?

Really not sure about it.

Maybe the annotation addon should listen on the  "aftercontextrestore" event https://github.com/georchestra/georchestra/blob/16.12/mapfishapp/src/main/webapp/app/js/GEOR_wmc.js#L44 to push its layer back to normal z-index.

**Comment by Gaetanbru** [comment] 2017-03-13 13:42
Thanx ! I think it's better like that but the "aftercontextrestore" event not exist on v15.12. We could adapt that.

**Comment by fvanderbiest** [comment] 2017-03-13 13:45
It's easy to backport https://github.com/georchestra/georchestra/commit/be769d2dd27555c84088f09e62ebb55e1abd378b to 15.12, right.

**Comment by Gaetanbru** [comment] 2017-04-05 22:52
Backport is done with success, really easy. I close this so, thank you.

**Comment by fvanderbiest** [comment] 2017-04-06 07:24
Please contribute back to the community, either through PR or patch.

**Comment by Gaetanbru** [comment] 2017-04-06 07:30
Yes, it was planned. Sorry to have closed this issue before.

**Closed** 2022-09-29 20:22 UTC
