### ISSUE TITLE
GeoNetwork 3.8 => 4.0.x

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3218] opened 2020-12-09 09:16 UTC
Time to upgrade ? 3.10.5 is the latest stable.

It brings lots of improvements over 3.8.x (UI, ldap sync, harvesters, etc)

**Comment by landryb** [comment] 2020-12-09 09:22
many bugs fixed, many bugs added ? ;)

**Comment by fxprunayre** [comment] 2020-12-09 10:21
Maybe geOrchestra should stop using versions that are not maintained and used by anyone unless you put someone to take care of it ? In all bugs reported on geOrchestra/GN in 2020, it is probably not wrong to say that all (or almost all) were already fixed in the 3.10.x branch and you spent (long) time digging into when/where it was fixed and try to backport rather than using the branch that the (limited number of) "core" GeoNetworkers are taking care of.

Current versions and usages
https://sourceforge.net/projects/geonetwork/files/GeoNetwork_opensource/ 

It is also true to say that it is probably not clear enough on GeoNetwork side to know who is supporting which versions for how long ... Today, we can probably say, GeoCat is supporting 3.10.x, I'm supporting 4.x. Camptocamp ?

Why not moving to 4.0.x and get even more bugs ...

**Comment by landryb** [comment] 2020-12-09 10:37
totally agree on the pointlessness of staying on an unsupported branch (georchestra has a long history of being a bit behind in terms of geonetwork releases ..), but geonetwork/core-geonetwork#4727 lists many features that are probably used by someone (i know for example we use the georss) that arent yet in 4.0.x.

**Comment by fxprunayre** [comment] 2020-12-09 10:47
> but [geonetwork/core-geonetwork#4727](https://github.com/geonetwork/core-geonetwork/issues/4727) lists many features that are probably used by someone (i know for example we use the georss) that arent yet in 4.0.x

It is good to have feedback on which ones are really missing. So don't hesitate to raise your needs. GeoRSS is also high on my list (but may be supported via OGC API Records on going implementation ...). Probably not the hardest one in the list though.

For geOrchestra, CAS may be important but @pmauduit made it work on 4.0.2 for Ifremer.

**Comment by landryb** [comment] 2020-12-09 10:52
i'm not sure how the cas integration is done in georchestra, but most other apps use headers coming from the sec-proxy to authenticate the user, i dont think its a direct 'cas integration'

**Comment by landryb** [comment] 2021-03-08 07:10
implementation of georss in v4 is tracked upstream in geonetwork/core-geonetwork#5332

**Comment by landryb** [comment] 2021-04-06 14:10
thing of importance: the GN->mapstore link requires mapstore to allow loading layers from an arbitrary external service/url, right now it only supports loading layers from sources present in mapstore catalog (cf https://mapstore.readthedocs.io/en/v2021.01.00/developer-guide/map-query-parameters/).

i think this has to be implemented mapstore-side first, dunno if there's already a tracking bug there.

**Comment by fvanderbiest** [comment] 2021-04-07 08:18
Also, everyone has to be aware of the missing bits, see https://github.com/geonetwork/core-geonetwork/issues/4727
eg :
 * results_with_summary gone means mapfishapp's "search layers in catalog" won't work anymore - basically this alone would be the latest nail in the coffin for the good old mapfishapp.
 * CSW GetDomain getDomain not implemented yet means mapfishapp's thesaurus search won't work anymore.
 * virtual csw is gone / replaced

**Comment by landryb** [comment] 2021-04-07 08:29
the 'portal' feature is a well-structured (&well-documented) replacement for virtual csw.

as for the other features.. well, that's the path of evolution, adapt or die, sadly. I'm not 100% sure mapstore is on par feature-wise wrt csw search, but at least that'll be an incentive to improve that ?

**Comment by landryb** [comment] 2021-07-20 14:21
for those following at home, work in progress by @pmauduit in https://github.com/georchestra/geonetwork/tree/georchestra-gn4-4.0.5, builds, havent tried running it yet.

**Comment by landryb** [comment] 2021-07-22 07:28
after a bit of fighting with es/kibana (cf georchestra/ansible#85), war built from the above branch works in a sample install (not docker), bits remaining (mostly geor customizations) and being worked on:
- [ ] geonetwork header sometimes jumps above georchestra header/iframe (and the latter url/height is harcoded so far, should come from datadir)
- [ ] logo at the left of the gn header seems lost, but that might be me messing with gn datadir
- [ ] gn map tab still enabled
- [ ] schemas need to be removed from the datadir/upgraded from the ones shipped by the webapp (eg update https://github.com/georchestra/geonetwork_minimal_datadir)
- [ ] wro4j* file needs to be recreated/removed otherwise there's a nonsensical javascript `alert()` popup with `ERROR: The config-summary.xml file does not declare a summary type of: 'details'` 
- [ ] some config still needs to be tweaked in the webapp (http://paste.debian.net/1205123/), work pending to use `$datadir/geonetwork/geonetwork.properties`
- [ ] debian packaging profile missing
- [ ] every hit on gn triggers 3 hits on kibana, feels strange...
- [ ] db migration from 3.8 works, except an error msg from https://github.com/geonetwork/core-geonetwork/blob/9504f940bcea08abe6aff36eecda907ae99c57cf/web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v3110/UpdateMetadataStatus.java#L80 (to be reported upstream ?)
```
2021-07-21 12:06:16,363 ERROR [geonetwork.database] -   Exception while adding new id column to MetadataStatus. Error is: ERROR: column "id" of relation "metadatastatus" already exists
2021-07-21 12:06:16,363 ERROR [geonetwork.database] -   Exception while adding new uuid column to MetadataStatus. Error is: ERROR: current transaction is aborted, commands ignored until end of transaction block
2021-07-21 12:06:16,547 ERROR [geonetwork.database] -   Exception while dropping old primary key on table MetadataStatus. Restart application and check logs for database errors.  If errors exists then may need to manually drop the primary key for this table. Error is: ERROR: syntax error at or near "primary"
  Position : 33
```

**Comment by pmauduit** [comment] 2021-07-22 13:50
I did a rapid test with Java11, I was able to compile (without running the tests though, which fail), and to run it in my docker compo, no issue so far but on a very limited runtime test scenario.

I was not confident enough to push it to the main working branch: https://github.com/georchestra/geonetwork/tree/java-11-compat even though it remains compatible and does the same thing when running with a Java8 environment.

**Comment by pmauduit** [comment] 2021-07-23 13:23
docker & debianPackage build should be ok now.

**Comment by landryb** [comment] 2021-07-26 06:15
> docker & debianPackage build should be ok now.

in which branch ? havent been able to find the corresponding commit for `debianPackage` profile, be it in `java-11-compat` or `georchestra-gn4-4.0.5`

**Comment by pmauduit** [comment] 2021-07-26 07:24
... I forgot to push ...

**Comment by landryb** [comment] 2021-07-26 08:51
> ... I forgot to push, it's in the gn4-4.0.5 branch now

tested ok:
```
[26/07 10:46] landry@build.fluela:/data/src/georchestra/georchestra/geonetwork $mvn clean install -DskipTests
[26/07 10:47] landry@build.fluela:/data/src/georchestra/georchestra/geonetwork $mvn clean install package deb:package -PdebianPackage -pl web
..
[WARNING] dpkg-deb: building package 'georchestra-geonetwork' in '/data/src/georchestra/georchestra/geonetwork/web/target/georchestra-geonetwork_4.0.5-0.20210726084821~ba94e7a-1_all.deb'.
```
the only strange thing is that the datadir branch being checked out was 20.0 and not master ? https://github.com/georchestra/geonetwork/commit/ba94e7abcb8a75a225720238ce02a6ba2da858d2#diff-06c528e8bf4bae607af1c54bfcfbb8f21c0d09a44cddb2851ffa08207dba3052R1240 should be fixed for 21.0 ;)

**Comment by pmauduit** [comment] 2021-07-26 09:20
yes indeed, no work has been done on the geor & gn datadirs yet.

**Comment by landryb** [comment] 2021-07-26 09:38
only small nit .. but im not sure this is something that can be fixable. previously the package was named `georchestra-geonetwork3` but now it's `georchestra-geonetwork`, and that causes issues when installing on a machine/vm/container which had the previous version:
```
sudo dpkg -i /tmp/georchestra-geonetwork_4.0.5-0.20210726084821~ba94e7a-1_all.deb 
(Reading database ... 92451 files and directories currently installed.)
Preparing to unpack .../georchestra-geonetwork_4.0.5-0.20210726084821~ba94e7a-1_all.deb ...
Unpacking georchestra-geonetwork (4.0.5-0.20210726084821~ba94e7a) ...
dpkg: error processing archive /tmp/georchestra-geonetwork_4.0.5-0.20210726084821~ba94e7a-1_all.deb (--install):
 trying to overwrite '/etc/georchestra/geonetwork/config/config-datadir-georchestra.xml', which is also in package georchestra-geonetwork3 3.8.2.202107051257~cd887b5
```
not fully sure how to properly handle that (besides `apt remove && apt install`..) but that will kill `apt upgrade` workflows :)

**Comment by pmauduit** [comment] 2021-07-26 09:43
bq. not fully sure how to properly handle that (besides apt remove && apt install..) but that will kill apt upgrade workflows :)

the georchestra-geonetwork -> georchestra-geonetwork3 came when we migrated from 2.x to 3.0.x, but I wondered if we needed a georchestra-geonetwork4 or if it was ok to stick with georchestra-geonetwork instead ? Shall we define something in the package metadata to indicate that gn3 has to be removed prior to install this new package ? and do we need to call it georchestra-geonetwork4 instead ?

**Comment by landryb** [comment] 2021-07-26 09:45
i had a very quick look and i dont think the debian maven plugin provides an easy way to handle such transitions - no need to bother about `georchestra-geonetwork4`, imo `georchestra-geonetwork` is fine.

**Comment by landryb** [comment] 2021-07-26 09:52
fwiw the map tab is still present so i dont think 0041c4785bdeb230cce03baa29e79ee162564ee3 removed the map tab.. i know its some setting in the db but the sql is ran only when creating/initializing a new db (ie, *works in docker* **(tm)**) but that doesnt handle existing db/configs :)

map tab indeed disappears if i manually execute https://github.com/georchestra/geonetwork/commit/0041c4785bdeb230cce03baa29e79ee162564ee3#diff-3bb14b615963ac1116f161d329bae4132323b6503d4387b02a6f2c46cd883393R742

**Comment by landryb** [comment] 2021-07-26 09:58
as for dcc7507e75df6f7c49b86f1c268c7085b739fe00, as is it probably only works in docker, i'm getting
```
exception

javax.servlet.ServletException: Trying to process targetUri init parameter: java.lang.NullPointerException
	org.fao.geonet.proxy.ConfigurableProxyServlet.initTarget(ConfigurableProxyServlet.java:17)
	org.mitre.dsmiley.httpproxy.ProxyServlet.init(ProxyServlet.java:173)
```
when going on the kibana tab within gn, so missing sane default ? (please make it default to **localhost** and not those silly docker names...).

OFC it's fine once i've locally added the two missing lines to `/etc/georchestra/geonetwork/geonetwork.properties` :)

**Comment by landryb** [comment] 2021-08-19 07:44
since my previous paste disappeared, here's (so far) what i had to tweak in the webapp for proper runtime within tomcat, removing the docker-style hardcoded hostnames:
```
--- classes/cache.ccf.orig      2021-07-26 11:42:09.209990368 +0200
+++ classes/cache.ccf   2021-07-26 11:42:23.086094243 +0200
@@ -14,7 +14,7 @@
 
 jcs.auxiliary.DC=org.apache.jcs.auxiliary.disk.indexed.IndexedDiskCacheFactory
 jcs.auxiliary.DC.attributes=org.apache.jcs.auxiliary.disk.indexed.IndexedDiskCacheAttributes
-jcs.auxiliary.DC.attributes.DiskPath=jcs_caching
+jcs.auxiliary.DC.attributes.DiskPath=/tmp/jcs_caching

 # XLink cache
 jcs.region.xlink=DC
--- config.properties.orig      2021-07-26 11:39:47.112926767 +0200
+++ config.properties   2021-07-26 11:40:15.757141153 +0200
@@ -13,7 +13,7 @@
 
 es.protocol=http
 es.port=9200
-es.host=elasticsearch
+es.host=localhost
 es.url=${es.protocol}://${es.host}:${es.port}
 es.username=
 es.password=
@@ -33,7 +33,7 @@
 es.index.searchlogs=gn-searchlogs
 es.index.searchlogs.type=searchlogs
 
-kb.url=http://kibana:5601/
+kb.url=http://localhost:5601/
 
 es.index.checker.interval=0/5 * * * * ?
--- config-geonetwork-georchestra.properties.orig       2021-08-19 09:42:50.543472628 +0200
+++ config-geonetwork-georchestra.properties    2021-07-26 11:40:42.381340428 +0200
@@ -18,12 +18,12 @@
 geonetwork.htmlcache.dir=${geonetwork.resources.dir}/htmlcache/
 
 # database configuration
-jdbc.host=database
+jdbc.host=localhost
 jdbc.port=5432
 jdbc.database=georchestra
 jdbc.schema=geonetwork
 jdbc.username=geonetwork
-jdbc.password=georchestra
+jdbc.password=geonetwork
 
 # The maximum number of active connections that can be allocated from this pool
 # at the same time, or negative for no limit
@@ -64,7 +64,7 @@
 
 
 # LDAP configuration
-ldap.url=ldap://ldap:389
+ldap.url=ldap://localhost:389
 ldap.base.dn=dc=georchestra,dc=org
 ldap.security.principal=cn=admin,dc=georchestra,dc=org
 ldap.security.credentials=secret

```

**Comment by landryb** [comment] 2021-08-19 14:38
testing a debian package built from 7c47f10, there's still an annoying warning at startup (in tomcat log) because `logs/geonetwork.log` is hardcoded somewhere before log4j config takes over:
```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: logs/geonetwork.log (Aucun fichier ou dossier de ce type)
        at java.io.FileOutputStream.open0(Native Method)
```
i suppose that comes from 
```
web/src/main/webapp/WEB-INF/classes/log4j.xml:    <param name="File" value="${log_dir}logs/geonetwork.log"/>
```
which is shipped in the webapp, and we dont set nor document `log_dir` anywhere. Something to fix, because it's annoying to look for startup logs in a different file than the one configured in log4j.xml.

there's also a vomit about the `jcs_caching` dir where gn tries to write:
```
14:16:30.412 [Catalina-utility-2] ERROR org.apache.jcs.auxiliary.disk.indexed.IndexedDiskCache - Region [JeevesCacheManagerETERNAL] Failure initializing for fileName: JeevesCacheManagerETERNAL and root directory: jcs_caching
java.io.FileNotFoundException: /jcs_caching/JeevesCacheManagerETERNAL.data (Aucun fichier ou dossier de ce type)
```

afaict tomcat *needs* a restart/fresh start to properly start the webapp, it cant reload it on the fly (eg `touch web.xml` only triggers horrors). A bit annoying/regression, but i guess we'll have to live with it.

after several restarts, it seems something is missing from 7c47f10 because the webapp fails to find es:
```
java.net.UnknownHostException: elasticsearch
```

**Comment by landryb** [comment] 2021-08-19 15:10
somewhat other related issues/PRs: #3475, #3476 and #3477

**Comment by landryb** [comment] 2021-08-19 16:41
georchestra/geonetwork@24a1084 gives me a 'working' gn4 which talks to es on localhost, with the `es.host` property and kibana url coming from the datadir.

```
/etc/georchestra/geonetwork $tail -5 geonetwork.properties
es.featureproxy.targeturi=http://localhost:9200/gn-features/{_}
es.protocol=http
es.port=9200
es.host=localhost
kb.url=http://localhost:5601
```

afaiui, geonetwork/core-geonetwork#5826 also needs tracking for proper log4j config ?

**Comment by pmauduit** [comment] 2021-08-19 16:48
> afaiui, [geonetwork/core-geonetwork#5826](https://github.com/geonetwork/core-geonetwork/pull/5826) also needs tracking for proper log4j config ?

yes, probably need to be synced with upstream at least

**Comment by landryb** [comment] 2021-08-20 06:50
the GN datadir repo is badly in need of an update, iirc i've copied `webapps/geonetwork/WEB-INF/data/config/schema_plugins/` to my testing GN datadir, but the damn schema validation job that seem to automatically trigger every 2h fills the logs with errors related to schematron files missing:
```
2021-08-20 06:00:12,295 ERROR [jeeves.xmlresolver] - Request on http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd failed.Bad server response: 'Not Found -- URI: http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd -- Response Code: 404'
2021-08-20 06:00:12,600 ERROR [jeeves.xmlresolver] - Request on http://schemas.opengis.net/gml/3.2.1/file:/srv/data/geonetwork/config/schema_plugins/iso19139/schema2007/xlink/xlink.xsd failed.Bad server response: 'Not Found -- URI: http://schemas.opengis.net/gml/3.2.1/file:/srv/data/geonetwork/config/schema_plugins/iso19139/schema2007/xlink/xlink.xsd -- Response Code: 404'
2021-08-20 06:00:13,146 ERROR [jeeves.xmlresolver] - Request on http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/https://schemas.isotc211.org/19139/-/gmx/1.0/gmx.xsd failed.Bad server response: 'Not Found -- URI: http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/https://schemas.isotc211.org/19139/-/gmx/1.0/gmx.xsd -- Response Code: 404'
2021-08-20 06:00:13,296 ERROR [geonetwork.datamanager] - WARNING: schematron xslt schematron-rules-inspire failed
java.nio.file.NoSuchFileException: /srv/data/geonetwork/config/schema_plugins/iso19139/schematron/schematron-rules-inspire.xsl
2021-08-20 06:00:13,296 ERROR [geonetwork.datamanager] - WARNING: schematron xslt schematron-rules-inspire-sds failed
java.nio.file.NoSuchFileException: /srv/data/geonetwork/config/schema_plugins/iso19139/schematron/schematron-rules-inspire-sds.xsl
2021-08-20 06:00:13,296 ERROR [geonetwork.datamanager] - WARNING: schematron xslt schematron-rules-inspire-strict failed
java.nio.file.NoSuchFileException: /srv/data/geonetwork/config/schema_plugins/iso19139/schematron/schematron-rules-inspire-strict.xsl
2021-08-20 06:00:13,314 ERROR [geonetwork.datamanager] - WARNING: schematron xslt schematron-rules-url-check failed
java.nio.file.NoSuchFileException: /srv/data/geonetwork/config/schema_plugins/iso19139/schematron/schematron-rules-url-check.report_only.xsl

**Comment by pmauduit** [comment] 2022-02-11 11:07
duplicates #3607

**Closed by pmauduit** 2022-02-11 11:07 UTC

**Comment by landryb** [comment] 2022-02-11 13:03
When i've redone more testing i'll reopen distinct issues for items still to fix/improve (cf https://github.com/georchestra/georchestra/issues/3218#issuecomment-884709762) - in the meantime yay for having this finally merged/closed/integrated :)
