### ISSUE TITLE
container docker-ldap-1 is unhealthy

### ISSUE THREAD

**Issue by omarlabidi** [georchestra/georchestra#4221] opened 2024-04-06 08:04 UTC
Hi ! 
I'm trying out GeOrchestra for the first time. I've set up the Docker composition, but I'm encountering an issue. I'm getting this error message: "dependency failed to start: container docker-ldap-1 is unhealthy". Any ideas on how to fix this? 

Thanks!

checking the log (docker logs docker-ldap-1) I get this

[INFO] No CUSTOM_SCRIPTS_DIRECTORY env variable set
run-parts: executing /docker-entrypoint.d/00-init
Info: Container already configured, therefore ignoring SLAPD_xxx environment variables and preseed files
run-parts: executing /docker-entrypoint.d/01-populate
LDAP already initialized !
run-parts: executing /docker-entrypoint.d/02-indexes
LDAP indexed
66110b86 @(#) 

Debian OpenLDAP Maintainers pkg-openldap-devel@lists.alioth.debian.org
66110b86 User Schema load failed for attribute "pwdAttribute". Error code 17: attribute type undefined
66110b86 config error processing olcOverlay={0}ppolicy,olcDatabase={1}mdb,cn=config: User Schema load failed for attribute "pwdAttribute". Error code 17: attribute type undefined
66110b86 slapd stopped.
66110b86 connections_destroy: nothing to destroy.

**Comment by omarlabidi** [comment] 2024-04-06 08:41
Ah, that's my mistake, I hadn't installed the updates (git checkout 23.0 && git submodule update). 
But I'm encountering another error message this time, which is (container docker-ldap-1 is unhealthy).

**Comment by fvanderbiest** [comment] 2024-04-08 08:34
Dupe of https://github.com/georchestra/docker/issues/279

**Closed by fvanderbiest** 2024-04-08 08:34 UTC
