### ISSUE TITLE
Geoserver : Permanent loop with HTTP 302

### ISSUE THREAD

**Issue by scali** [georchestra/georchestra#2668] opened 2019-07-31 10:19 UTC
When testing the link  https://my.server.fqdn/geoserver or when using the link "Services" in geOrchestra (which redirect to https://my.server.fqdn/geoserver/web/) I've got a permanent redirection with a HTTP 302 status .
 
When capturing the network activity on my browser, I got this :

![gg](https://user-images.githubusercontent.com/2387149/62203879-55ee8880-b38c-11e9-9268-e27d57e20246.PNG)

I used the configuration from the "middleware setup" installation documentation for geOrchestra 19.04, and I can't see if  it's the apache proxy or the security-proxy that are doing this redirection loop.

**Comment by fvanderbiest** [comment] 2019-08-14 13:00
I'm not sure I understand what's happening here.
Do you see geoserver UI on /geoserver/web ?

**Comment by scali** [comment] 2019-08-19 07:42
Hi,

No, I can't see the UI.

Here is the sequence happens I suppose :

`/geoserver/` is, behind the scene, the default path `/geoserver/index.html` **OK**
`/geoserver/index.html` redirects to `/geoserver/web/` **OK**
geoserver (the software) adds the `/?xxxx` parameter **OK**
`/geoserver/web/?xxxx` seems to be rewrited to `/geoserver/?xxxx`  (so the sequence restarts to the begin, and loop over and over) **NOK**

By the way, what's the point of the /?xxxx parameter ?

**Comment by RemiDesgrange** [comment] 2019-08-19 08:40
Can you link the doc you used ? Did you use `apache` to deploy georchestra  ? Or docker ? Or anything else ? it seems like proxy misconfiguration

**Comment by scali** [comment] 2019-08-19 08:55
Here is the doc I used : https://github.com/georchestra/georchestra/blob/19.04/docs/setup/apache.md
and the version of apache is `Apache/2.4.29`

My `geoserver.conf` is strictly the one from the doc

**Comment by RemiDesgrange** [comment] 2019-08-19 13:37
ping @landryb ?

**Comment by landryb** [comment] 2019-08-19 14:24
I think i've seen something vaguely similar in the past, and i had to hack something somewhere in the security proxy - there are wayyy too many redirections. I still have nightmares about it.

There was #2603 but i think it's fixed in 19.04 and that wasnt about geoserver.

**Comment by hsquividant** [comment] 2019-09-25 08:56
Hello from the far west !
I reproduce the same issue with exactly the same context, deploying from scratch geor 19.04 / datadir / generic wars.
I 've try another test by deploying Geoserver 2.16 stable release. that works in standalone tomcat but not behind geor security proxy. For example, in UI, before you click on Layer preview menu, you see the link https://geoaco.agrocampus-ouest.fr/geoserver/web/wicket/bookmarkable/org.geoserver.web.demo.MapPreviewPage, but when you really click on it, the URL changes to https://geoaco.agrocampus-ouest.fr/geoserver/org.geoserver.web.demo.MapPreviewPage (404 error)
Does security proxy rewrite to this wrong URL? If right, it seems to be security proxy regression.
Does anybody deployed successfully from scratch this new 19.04 release in this context ? 
Thanks for any help
Hervé

**Comment by pierrejego** [comment] 2019-09-25 09:55
Hello hsquividant, 
your error is not link to this issue, but I actually have the same on a 19.04 with geoserver 2.15. Main page is working but I have a white page when I try to deploy a layer, and 404 when I try to preview. I am still debbuging, I'll discuss about it on  google groups once I found the reason.

**Comment by hsquividant** [comment] 2019-09-25 10:25
Hello Pierre
Thanks for your answer. First I've reproduced exactly Sacli #2668 issue with infinite loop on Geoserver (downloaded here https://packages.georchestra.org/bot/wars/19.04/geoserver-generic.war) Interface.
In second time, as you, I've tried to deploy GS stable release with excalty same issue you have (main page is working but preview page in 404 error). Maybe this 2 issues have a link, maybe not. My intuition is that it could be du to the same mistaken rewrite rule from security proxy. Very interested bye your debug results...

**Comment by pierrejego** [comment] 2019-10-03 22:19
For the 404, I think you need to change your <Context> balise to <Context useRelativeRedirects="false"> in your tomcat context.xml configuration file.

But for the loop, I didn't manage to reproduce it, I don't know how to fixe it.

**Comment by hsquividant** [comment] 2019-10-07 16:37
For me, it solved permanent loop issue too

**Comment by fvanderbiest** [comment] 2019-10-11 13:56
@pmauduit had reported the need to set `useRelativeRedirects="false"` on https://github.com/georchestra/georchestra/pull/1847 but this was rather confidential.

We should update the official documentation and the ansible deployer to take this into account.

**Closed** 2019-10-11 14:28 UTC

**Comment by pmauduit** [comment] 2019-10-12 17:33
Rather confidential, but still documented:
https://github.com/georchestra/georchestra/blob/19.04/docs/setup/tomcat.md#create-the-instance-2

**Comment by landryb** [comment] 2019-10-15 07:28
> We should update the official documentation and the ansible deployer to take this into account.

like georchestra/ansible@b9fb398c 16 months ago ? ;)

**Comment by fvanderbiest** [comment] 2019-10-15 07:35
Waou, I do not even remember I did this ...

**Comment by landryb** [comment] 2019-10-15 07:38
Now i remember that #2193 was also causing redirect loops but that got fixed
