### ISSUE TITLE
geoserver - some tiles cannot be generated on raster data

### ISSUE THREAD

**Issue by severo** [georchestra/georchestra#2324] opened 2018-12-11 14:20 UTC
**Describe the bug**

Sometimes the images generated by GeoServer on raster data contain black rectangles/tiles.

**geOrchestra version or branch**

18.06, with GeoServer 2.12

**To Reproduce**

1. Go to https://www.geograndest.fr/geoserver/ref/wms?service=WMS&version=1.1.0&request=GetMap&layers=ref:REF_EUDEM30_NB_2013_TIFLZW_ETRS80&styles=&bbox=-35.0,30.000000000000036,44.99999999999994,75.0&width=768&height=431&srs=EPSG:4258&format=application/openlayers
2. Play with the zoom and the pan, until black rectangles appear in the image generated by GeoServer

**Expected behavior**

The image generated by GeoServer shouldn't include black "tiles".

**Screenshots**

Screenshots:

![captura de pantalla de 2018-12-11 10-13-28](https://user-images.githubusercontent.com/1676121/49806187-70a4bc00-fd2d-11e8-9ffd-0044e13c4527.png)
![captura de pantalla de 2018-12-11 10-12-33](https://user-images.githubusercontent.com/1676121/49806190-74d0d980-fd2d-11e8-8e94-20ecd8449a29.png)

The generated image (note that in that case, GeoServer generated a complete image, but it seems that it is composed by sub-tiles, and that some of them could not be generated):

![canvas](https://user-images.githubusercontent.com/1676121/49806216-84502280-fd2d-11e8-8071-194614b7da4b.png)

**Comment by fvanderbiest** [comment] 2018-12-11 18:52
Not sure this is an issue with GeoServer itself. 

Might be due to data storage, JVM memory management in docker container, ...

**Comment by fvanderbiest** [comment] 2019-01-16 11:58
Not happening anymore. Closing

**Comment by fvanderbiest** [comment] 2019-02-13 10:23
Still happening with https://www.geograndest.fr/geoserver/wms?CRS=EPSG%3A4326&FORMAT=image%2Fpng&MAP_RESOLUTION=300&STYLES=&WIDTH=2000&HEIGHT=1772&LAYERS=REF_EUDEM30_NB_2013_TIFLZW_ETRS80&REQUEST=GetMap&BBOX=44.13835783208205754%2C3.28764834252515437%2C47.8936054101229729%2C7.52455652043046896&FORMAT_OPTIONS=dpi%3A300&VERSION=1.3.0&SERVICE=WMS&DPI=300&TRANSPARENT=TRUE

**Comment by fvanderbiest** [comment] 2019-02-13 10:24
IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.write0(FileDispatcherImpl.java)
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
at sun.nio.ch.IOUtil.write(IOUtil.java:65)
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
...
(111 additional frame(s) were not displayed)

EofException: None
at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:286)
at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:429)
at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:323)
at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:810)
...
(106 additional frame(s) were not displayed)

**Comment by fvanderbiest** [comment] 2019-02-13 10:41
It should be noted that black rectangles do not always appear at the same place and are not reproducible every time.

**Comment by fvanderbiest** [comment] 2019-02-13 10:42
@groldan any idea ?

**Comment by fvanderbiest** [comment] 2019-03-04 12:09
Fixed by disabling `tile recycling` in JAI settings page. Kudos to @groldan !

**Closed by fvanderbiest** 2019-03-04 12:09 UTC
Labels: 18.06, bug

**Comment by severo** [comment] 2019-03-04 12:35
Maybe we need to document that somewhere.
