### ISSUE TITLE
Account creation page link is NOK

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1234] opened 2016-02-09 14:39 UTC
On https://sdi.georchestra.org/cas/login, the "create account" link points to https://sdi.georchestra.org/cas/null/account/new instead of https://sdi.georchestra.org/ldapadmin/account/new

**Comment by pmauduit** [comment] 2016-02-09 18:15
I cannot reproduce with several different environments, and by looking at sdi.g.o:

- the tomcat-01 running CAS is version 6 !
- It was running on an old jvm (6), I upgraded to java7 but this did not fix the problem ;

I guess we can consider that this is working on newer versions, and to fix it on sdi more specifically, change the values in the JSPs in the sdi.g.o profile (since the JSP are customized in the configuration).

**Comment by pmauduit** [comment] 2016-02-09 18:37
Ok, got it, there is a scope problem with the generated Java from the JSP compilation:

```java
    try {
      response.setContentType("text/html; charset=UTF-8");

[...]
String sharedInstanceName = "geOrchestra demo";
String sharedHomepageUrl = "https://sdi.georchestra.org/";
String sharedHeaderHeight = "90";
String sharedLdapadminContextpath = "/ldapadmin";

try {
  ApplicationContext ctx = RequestContextUtils.getWebApplicationContext(request);
  sharedInstanceName = ctx.getBean(GeorchestraConfiguration.class).getProperty("instance.name");
  sharedHomepageUrl = ctx.getBean(GeorchestraConfiguration.class).getProperty("homepage.url");
  sharedHeaderHeight = ctx.getBean(GeorchestraConfiguration.class).getProperty("header.height");
  sharedLdapadminContextpath = ctx.getBean(GeorchestraConfiguration.class).getProperty("ldapadmin.contextpath");
  } catch (Exception e) {
}


      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <title>CAS - ");
      out.print( sharedInstanceName );

[...]
```

**Comment by pmauduit** [comment] 2016-02-09 18:41
Same JSP generated by Jetty:

```java
String sharedInstanceName = "geOrchestra";
String sharedHomepageUrl = "https://georchestra.mydomain.org/";
String sharedHeaderHeight = "90";
String sharedLdapadminContextpath = "/ldapadmin";

try {
  ApplicationContext ctx = RequestContextUtils.getWebApplicationContext(request);
  sharedInstanceName = ctx.getBean(GeorchestraConfiguration.class).getProperty("instance.name");
  sharedHomepageUrl = ctx.getBean(GeorchestraConfiguration.class).getProperty("homepage.url");
  sharedHeaderHeight = ctx.getBean(GeorchestraConfiguration.class).getProperty("header.height");
  sharedLdapadminContextpath = ctx.getBean(GeorchestraConfiguration.class).getProperty("ldapadmin.contextpath");
  } catch (Exception e) {
}


      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("\n");
      out.write("  <title>CAS - ");
      out.print( sharedInstanceName );
```

Should we deprecate tomcat6 ? rewriting this variable substitution to support end-of-life / deprecated libs will be a timeloss from my point of view ...

**Comment by pmauduit** [comment] 2016-02-10 09:09
There actually is an issue in case of non-datadir mode: GeorchestraConfiguration.getProperty() is still called and returning null since the bean exists, we have to add an extra check before reaffecting variables in the try {} catch block. (GeorchestraConfiguration.isActivated()).

**Comment by pmauduit** [comment] 2016-02-10 10:15
Fixed in the template once https://github.com/georchestra/template/pull/24 is merged. sdi.g.o profile up to date and already deployed.

**Closed by pmauduit** 2016-02-10 10:15 UTC
Labels: 1 - Ready, bug, priority-top
