### ISSUE TITLE
[19.04] MAPFISHAPP - Addon ATLAS - Error 404 :  https://georchestra.mydomain.org/atlas/print/capabilities.json

### ISSUE THREAD

**Issue by bendeg** [georchestra/georchestra#2822] opened 2019-11-14 08:55 UTC
**Describe the bug**
error 404

**To Reproduce**
I try to use the ATLAS addon, and since I use the datadir, I enabled it in /etc/georchestra/mapfishapp/addons/atlas/config.json.

ATLAS addon is indeed enabled (I can see it in the list) and I can add it to the current list of tools.

But, when I try to use it : error 404, ressource unavailable.

- URL is **https://georchestra.mydomain.org/atlas/print/capabilities.json**

- In /etc/georchestra/mapfishapp/addons/atlas/config.json : **"atlasServerUrl": "/atlas/print"**

Is this URL pointing to /var/lib/tomcat-georchestra/webapps/atlas/print/ ?
If that's the case, there's no "print" folder or subfolder anywhere under ...webapps/atlas

- I can see /tmp/atlas

I must confess, I'm really confused on this one because apparently there're 2 types of configuration : client-side and server-side. I think I'm on the right track, but I can't see any **capabilities.json** file anywhere...
Should I create it ? And where exactly ?

**Comment by fvanderbiest** [comment] 2019-11-14 09:31
You're indeed on the good track, you need a server side component, which can be found here: https://packages.georchestra.org/bot/wars/19.04/atlas-generic.war

**Comment by fvanderbiest** [comment] 2019-11-14 09:33
Two things here for us:
 * if this question is being asked, this means we need an improved documentation on atlas deployment 
 * the `makefile` does not build the atlas webapp: https://github.com/georchestra/georchestra/blob/19.04/Makefile

**Comment by bendeg** [comment] 2019-11-14 09:39
I did already installed atlas.war and /var/lib/tomcat-georchestra/atlas/ exists

**Comment by fvanderbiest** [comment] 2019-11-14 09:53
What is the output of `curl http://localhost:8080/atlas/print/capabilities.json` (or equivalent) on your server ?
Did you route the atlas webapp with your reverse proxy / security-proxy (targets-mapping.properties) ?

**Comment by bendeg** [comment] 2019-11-14 10:49
here's my targets-mapping.properties : 

```analytics=http://localhost:8280/analytics/
atlas=http://localhost:8280/atlas/
console=http://localhost:8280/console/
extractorapp=http://localhost:8280/extractorapp/
geonetwork=http://localhost:8280/geonetwork/
geoserver=http://localhost:8380/geoserver/
header=http://localhost:8280/header/
mapfishapp=http://localhost:8280/mapfishapp/
```
========================================================================
curl http://localhost:8180/atlas/print/capabilities.json
AND
curl http://localhost:8280/atlas/print/capabilities.json

give me : 

```org.json.JSONException: Duplicate key "name"
	at org.json.JSONWriter.key(JSONWriter.java:219)
	at org.mapfish.print.attribute.PrimitiveAttribute.printClientConfig(PrimitiveAttribute.java:80)
	at org.mapfish.print.config.Template.printClientConfig(Template.java:111)
	at org.mapfish.print.config.Configuration.printClientConfig(Configuration.java:249)
	at org.mapfish.print.MapPrinter.printClientConfig(MapPrinter.java:73)
	at org.georchestra.atlas.CamelMapfishPrintComponent.printCapabilities(CamelMapfishPrintComponent.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.camel.component.bean.MethodInfo.invoke(MethodInfo.java:408)
	at org.apache.camel.component.bean.MethodInfo$1.doProceed(MethodInfo.java:279)
	at org.apache.camel.component.bean.MethodInfo$1.proceed(MethodInfo.java:252)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:177)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:68)
	at org.apache.camel.component.bean.BeanProducer.process(BeanProducer.java:38)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87)
	at org.apache.camel.http.common.CamelServlet.service(CamelServlet.java:143)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1458)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fvanderbiest** [comment] 2019-11-14 12:31
Dupe of #2774 then...

**Closed by fvanderbiest** 2019-11-14 12:31 UTC
