### ISSUE TITLE
mapfishapp : interrogation all layers

### ISSUE THREAD

**Issue by lecault** [georchestra/georchestra#1845] opened 2017-12-14 15:57 UTC
Hi,

In the mapfishapp 16.12 there's a regression : the interrgation of all layers is buged.

Example in GeoBretagne : perimeter of EPCI and commune are selected but attribute of only commune  : 

![interrog_all](https://user-images.githubusercontent.com/5269430/34000835-a8c15884-e0ee-11e7-9972-2420fed045a9.PNG)

It's same in PPIGE but ok in 15.12 plateform like GeoGrandEst or PIGMA.

Thank's.

**Comment by fvanderbiest** [comment] 2017-12-14 15:59
Confirmed, also witnessed on GeoRhena.

**Comment by fvanderbiest** [comment] 2017-12-26 10:53
This happens in https://github.com/georchestra/georchestra/blob/8a0ffd7ff2b6d783401ab139431d8f4d763fafd6/mapfishapp/src/main/webapp/app/js/GEOR.js#L464-L482
... 2 tabs are generated & inserted in the southpanel, but only one is visible.

This is strange, since this code did not change since 4 years...

**Comment by fvanderbiest** [comment] 2017-12-26 13:44
This code is a true nightmare...

It's impossible to let the user open tabs to display new results **and at the same time** to query aggregated layers. I'll see if I succeed to clean this horrible mess...

**Comment by fvanderbiest** [comment] 2017-12-27 10:31
Fixed on 16.12 with https://github.com/georchestra/georchestra/pull/1858

**Closed** 2017-12-27 10:31 UTC
Labels: 16.12, bug
