### ISSUE TITLE
console - remove Organisation type

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#4367] opened 2024-11-21 09:04 UTC
This dropdown seems really useless to me: 
![image](https://github.com/user-attachments/assets/83301648-8d9d-4519-9cea-d825cc771414)

I think we can remove it (+ the ldap stuff mapped onto `businessCategory` + the static list https://github.com/georchestra/datadir/blob/6c247aaa4c82e3a81ebd407d58d1b4c387fa4ec5/console/console.properties#L157-L159 ) for the upcoming geOrchestra version.

To be confirmed by community here or elsewhere.

**Comment by landryb** [comment] 2024-11-21 09:07
dupe of #4129 ? ;)

**Closed** 2024-11-21 09:12 UTC
Labels: gardening
