### ISSUE TITLE
GeoServer 2.8 + GeoFence 3

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1135] opened 2015-11-27 08:52 UTC
Some preliminary work has been done in https://github.com/pmauduit/georchestra/tree/georchestra-datadir-gs-28-gr-3 but we still need to:
 * update to 2.8.1
 * apply Niels' patches to GeoServer (see https://github.com/geoserver/geoserver/pull/1348 & https://github.com/geoserver/geoserver/pull/1352)
 * handle GeoSolution patches for delegated admin in GeoFence and better GeoServer embedding.
 * check everything works as expected

**Comment by pmauduit** [comment] 2015-12-03 09:30
- [] Rebasing onto 2.8.1
- [] integrating geoserver#1348
- [] integrating geoserver#1352

**Comment by pmauduit** [comment] 2015-12-03 10:31
Tests:
- [x] compilation
- [x] testsuite
- [ ] runtime

Some glitches at runtime: some weird wicket errors on some pages:

```
2015-12-03 10:27:38,201 ERROR [wicket.RequestCycle] - no get method defined for class: class org.apache.wicket.markup.resolver.MarkupInheritanceResolver$TransparentWebMarkupContainer expression: build
org.apache.wicket.WicketRuntimeException: no get method defined for class: class org.apache.wicket.markup.resolver.MarkupInheritanceResolver$TransparentWebMarkupContainer expression: build
	at org.apache.wicket.util.lang.PropertyResolver.getGetAndSetter(PropertyResolver.java:434)
	at org.apache.wicket.util.lang.PropertyResolver.getObjectAndGetSetter(PropertyResolver.java:240)
	at org.apache.wicket.util.lang.PropertyResolver.getValue(PropertyResolver.java:90)
	at org.apache.wicket.markup.resolver.WicketMessageResolver$MessageContainer$1.getValue(WicketMessageResolver.java:272)
	at org.apache.wicket.util.string.interpolator.VariableInterpolator.toString(VariableInterpolator.java:138)
	at org.apache.wicket.markup.resolver.WicketMessageResolver$MessageContainer.renderMessage(WicketMessageResolver.java:245)
	at org.apache.wicket.markup.resolver.WicketMessageResolver$MessageContainer.onComponentTagBody(WicketMessageResolver.java:210)
	at org.apache.wicket.Component.renderComponent(Component.java:2686)
	at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1538)
	at org.apache.wicket.Component.render(Component.java:2517)
	at org.apache.wicket.MarkupContainer.autoAdd(MarkupContainer.java:229)
	at org.apache.wicket.markup.resolver.WicketMessageResolver.resolve(WicketMessageResolver.java:148)

```

**Comment by fvanderbiest** [comment] 2015-12-03 10:38
Maybe @NielsCharlier can help with/check your integration of his patches.

**Comment by pmauduit** [comment] 2015-12-03 11:02
I'm encountering errors at compilation level:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project gs-web-core: Compilation failure: Compilation failure:
[ERROR] /home/pmauduit/projects/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/main/java/org/geoserver/web/data/resource/BasicResourceConfig.java:[160,50] error: cannot find symbol
[ERROR] variable cb of type CatalogBuilder
[ERROR] /home/pmauduit/projects/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/main/java/org/geoserver/web/data/layergroup/LayerGroupEditPage.java:[201,52] error: cannot find symbol
[ERROR] -> [Help 1]

```
Seems that several methods are missing between 2.8.1 tag and the master branche. Trying to backport them by hand anyway.

**Comment by pmauduit** [comment] 2015-12-03 12:04
Geoserver module compiles now without error (with tests activated) - I just needed to backport several missing methods.

**Comment by pmauduit** [comment] 2015-12-03 12:46
Runtime almost OK, just the "about geoserver" failing with my runtime testsuite:

```
2015-12-03 12:43:14,258 ERROR [wicket.RequestCycle] - no get method defined for class: class org.apache.wicket.markup.resolver.MarkupInheritanceResolver$TransparentWebMarkupContainer expression: build
org.apache.wicket.WicketRuntimeException: no get method defined for class: class org.apache.wicket.markup.resolver.MarkupInheritanceResolver$TransparentWebMarkupContainer expression: build
        at org.apache.wicket.util.lang.PropertyResolver.getGetAndSetter(PropertyResolver.java:434)
[...]
```

I was able to add a shapefile as a new layer, modifying the contact info of the server ....

**Comment by pmauduit** [comment] 2015-12-04 14:56
@NielsCharlier We can set a metadataUrl on a layer group, but it does not appear in the WMS get capabilities document, did I miss something ?

**Comment by NielsCharlier** [comment] 2015-12-07 10:14
It does on my branch. Looking at your branch, it seems you forgot to merge some of my changes.
All of the getCapabilities stuff is here: https://github.com/NielsCharlier/geoserver/commit/1288c6e669a2f39c79d07679449cdd1d19319f8b
You seemed to have missed that.

**Comment by pmauduit** [comment] 2015-12-07 12:16
@NielsCharlier Ok, mainly because NielsCharlier/geoserver@1288c6e is not part of any of the 2 PRs above. If I take this specific commit, is there anything else I'm missing from your master branche ?

**Comment by NielsCharlier** [comment] 2015-12-07 12:28
There were three PRs, the first one has been merged a few weeks ago. That is it.

**Comment by pmauduit** [comment] 2015-12-07 12:35
Ok, my mistake, I was not aware of it, thanks

**Comment by pmauduit** [comment] 2015-12-07 12:37
Missing PR from the previous comments: https://github.com/geoserver/geoserver/pull/1335

**Comment by pmauduit** [comment] 2015-12-07 17:23
Ok, done it compiles, I need to check at runtime that everything is ok now.

**Comment by pmauduit** [comment] 2015-12-08 10:41
Tested at runtime, I now have the metadataUrl for layergroups. I created a new branch in my own repo, and removed the old one:

- https://github.com/pmauduit/georchestra/tree/gs-281-layergroups-gf-3
Which complies with the current one of GeoServer:

- https://github.com/pmauduit/geoserver/tree/2.8.1-layergroups-georchestra

**Comment by fvanderbiest** [comment] 2015-12-08 10:54
So, everything looks good ? -> Merge

**Comment by pmauduit** [comment] 2015-12-08 10:57
No, still a minor bug with the "about geoserver" interface

**Comment by fvanderbiest** [comment] 2015-12-22 14:00
Still TODO: handle GeoSolution patches for delegated admin in GeoFence and better GeoServer embedding, cf below (from Emanuele).
But let's wait they have backported their patches to 2.8.x before that.

Implementation is complete:
- GeoFence repo has been branched; the 3.0.x is the new stable branch,
- The new features have been committed on master (3.1-SNAPSHOT)
   https://github.com/geoserver/geofence/issues/67

- The administration UI for the new rules is ready for both master and 2.8.x,
yet not merged:
- https://osgeo-org.atlassian.net/browse/GEOS-7356
- PR #1376
   [GEOS-7356] Add GeoFence admin rules page
- PR #1380
   [GEOS-7356] Add GeoFence admin rules page (backport to 2.8.x)

The improvements for the GeoServer UI are ready as well:
- PR #1367
 [GEOS-7347] Allow to enter an allowed area in Geofence UI
- PR #1379
 [GEOS-7347] Allow to enter an allowed area in Geofence UI (backport to 2.8.x)

- PR #1368
    [GEOS-7348] Rules priority can be managed using drag and drop
- PR #1378
    [GEOS-7348] Rules priority can be managed using drag and drop (backport to
    2.8.x)

- The probe is ready, but has not been committed yet:
   https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-7350

**Comment by pmauduit** [comment] 2015-12-22 14:26
About the "about geoserver" issue, I cannot reproduce with the current version of the package available from the CI.

**Comment by pmauduit** [comment] 2015-12-24 16:02
Seems incompatible with the work provided by Niels, trying to merge upstream/2.8.x / clean install gives the following:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.3:test (default-test) on project gs-wms: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/wms/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project gs-web-core: Compilation failure: Compilation failure:
[ERROR] /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java:[38,40] error: cannot find symbol
[ERROR] /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java:[255,25] error: cannot find symbol
[ERROR] class AbstractAdminPrivilegeTest
[ERROR] /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java:[256,34] error: cannot find symbol
[ERROR] class AbstractAdminPrivilegeTest
[ERROR] /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java:[269,25] error: cannot find symbol
[ERROR] class AbstractAdminPrivilegeTest
[ERROR] /home/pmauduit/src/georchestra/georchestra/geoserver/geoserver-submodule/src/web/core/src/test/java/org/geoserver/web/admin/AbstractAdminPrivilegeTest.java:[270,34] error: cannot find symbol
[ERROR] -> [Help 1]

```

**Comment by pmauduit** [comment] 2016-01-07 14:02
After another retry, I've got some tests failing onto gs-wms:

```
Failed tests:   testIndexedTransparency(org.geoserver.wms.map.GetMapIntegrationTest): expected:<[image/png]> but was:<[application/vnd.ogc.se_xml]>
  testFourBits(org.geoserver.wms.map.GetMapIntegrationTest): expected:<[image/png]> but was:<[application/vnd.ogc.se_xml]>
  testCascadeGetMapOnto110(org.geoserver.wms.wms_1_1_1.WMSCascadeTest): expected:<[image/png]> but was:<[text/xml]>
  testCascadeGetMapOnto130(org.geoserver.wms.wms_1_1_1.WMSCascadeTest): expected:<[image/png]> but was:<[text/xml]>
  testCascadeGetMapOnto11(org.geoserver.wms.wms_1_3.WMSCascadeTest): expected:<[image/png]> but was:<[text/xml]>
  testCascadeGetMapOnto13(org.geoserver.wms.wms_1_3.WMSCascadeTest): expected:<[image/png]> but was:<[text/xml]>

```

I've got the same errors trying to run the testsuite on upstream/3.0.x (i.e. the official GeoServer branche, with no geOrchestra-related modifications).

Maven command used to launch the testsuite:

```
$ mvn clean install
```

**Comment by pmauduit** [comment] 2016-01-24 19:33
> About the "about geoserver" issue, I cannot reproduce with the current version of the package available from the CI.

I found out why, see here for the detailed explanation:
https://github.com/georchestra/geoserver/commit/3e1cda050b71246e04478eeef4cbfbccbb063959

Even with a broken testsuite, it seems to work at runtime smoothly, due to the time constraints related to the release, shall we consider accepting the failing tests ?

**Comment by fvanderbiest** [comment] 2016-01-25 14:03
> shall we consider accepting the failing tests

OK

**Closed** 2016-02-08 07:54 UTC
Labels: 2 - Working
