### ISSUE TITLE
[console] user + org validation provides inconsistent messages

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2892] opened 2020-01-21 15:28 UTC
my colleagues experienced this one several times, if a new user and new org is to be validated, if
 - you go to the pending user page, there's a red banner advising first to validate the corresponding pending org (which is fine, it makes 100% sense)
- if you click on the corresponding link and validate the pending org
- then click back on the users tab to get back to the pending users list
- then to the pending user, **the red banner advising to validate the org is still present**, which confuses the admin a lot.
(note that at no time the useradmin clicked on the *previous* button in the browser)

I suppose that's because the json info fpr the pending user wasnt reloaded/refreshed from the console backend ?

**Comment by landryb** [comment] 2020-01-21 15:29
thats on 19.04 btw.

**Comment by tonio** [comment] 2020-01-23 10:09
I test this on master (FF & chrome, devtools not opened) & cannot reproduce.
Is there a reproducible way of observing it? Thanks.

**Comment by landryb** [comment] 2020-01-23 12:50
str on console master:
* create pending acct/org via `console/account/new`
* login as admin
* click on a pending user -> yields GET reqs on `console/private/users/<pendingusername>` & `console/private/users/<pendingorg>`
* click on the link in the red banner (`Pending user — Confirm organization first : ORG1 `)
* confirm pending org, yields a PUT on `console/private/orgs/<pendingorg>`
* click on users tab header, yields a GET on`console/private/users` & `console/private/roles`
* click on pending user list, then the pending user link -> properly yields again a GET on `console/private/orgs/<org>` and the pending org msg isnt shown this time.

This is on master, maybe that bug has been fixed since 19.04, will try to repro on 19.04.

I'll have to ask my colleagues again, but they probably found a way to trigger this, but you needto understand that i cant ask them to use the network console everytime they validate a user.. i insisted to make sure they were not using the previous/back button in the browser, but who knows.

**Comment by fvanderbiest** [comment] 2021-12-17 08:56
We could not reproduce locally on master => probably fixed in between, yup !

**Closed by fvanderbiest** 2021-12-17 08:56 UTC
Labels: question
