### ISSUE TITLE
LDAPS protocol is not supported since 19.04

### ISSUE THREAD

**Issue by jusabatier** [georchestra/georchestra#2648] opened 2019-07-08 14:53 UTC
Since 19.04 and the use of the new datadir structure, the ldaps protocole isn't supported anymore.

As we only set the host and port for LDAP but not the protocol, and ldap:// is hardcoded in the config of georchestra's apps.

**Comment by fvanderbiest** [comment] 2019-07-23 07:46
Right, it's a regression indeed. 
Thanks for the report.

We should add a `ldapScheme` var in the datadir's `default.properties`. 
@RemiDesgrange will take care of it.

**Comment by fvanderbiest** [comment] 2019-07-23 07:51
BTW, I see that the security-proxy does not use the `ldapPort` property - this should be fixed at the same time.

**Comment by fvanderbiest** [comment] 2019-07-23 07:52
To be fixed on 19.04, since it's a regression.

**Closed** 2019-07-24 13:25 UTC
Labels: 19.04, bug, priority-top
